/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Utilitários.ConectaBanco;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.event.CaretEvent;
import javax.swing.event.CaretListener;

/**
 *
 * @author Jorge
 */
public class TelaProdutos extends javax.swing.JFrame {
    /**
     * Creates new form Principal
     */
    public TelaProdutos() {
        initComponents();
        preencherTabela("select * from Produto order by idProduto;");
        campoID.addCaretListener(listener);
    }
    
    ConectaBanco conecta = new ConectaBanco();
    
    private void preencherTabela(String SQL){
     ArrayList dados = new ArrayList();
     
     String [] Colunas = new String[]{"ID","Nome","Preço","Descrição"};
     
     conecta.executaSQL(SQL);
     
        try {
            conecta.rs.first();
            
            do{
                dados.add(new Object[]{conecta.rs.getInt("idProduto"),
                                       conecta.rs.getString("nomeProduto"),
                                       conecta.rs.getDouble("precoProduto"),
                                       conecta.rs.getString("descricaoProduto")});
            }while(conecta.rs.next());
        }
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"Erro ao preencher ArrayList! Erro:" + ex);
        }
     
        ModeloTabela modelo = new ModeloTabela(dados, Colunas);
        Tabela.setModel(modelo);
        Tabela.getColumnModel().getColumn(0).setPreferredWidth(40);
        Tabela.getColumnModel().getColumn(0).setResizable(false);
        Tabela.getColumnModel().getColumn(1).setPreferredWidth(180);
        Tabela.getColumnModel().getColumn(1).setResizable(false);
        Tabela.getColumnModel().getColumn(2).setPreferredWidth(60);
        Tabela.getColumnModel().getColumn(2).setResizable(false);
        Tabela.getColumnModel().getColumn(3).setPreferredWidth(60);
        Tabela.getColumnModel().getColumn(3).setResizable(false);
        Tabela.getTableHeader().setReorderingAllowed(false);
        Tabela.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        Tabela.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }
    
        CaretListener listener = new CaretListener() {
        @Override
        public void caretUpdate(final CaretEvent e) {
            //faz as verificações necessárias.. tamanho de campo, validação, etc.
            if(campoID.getText().length() > 0){
                botaoExcluir.setEnabled(true);
                botaoAlterar.setEnabled(true);
                botaoAdicionar.setEnabled(false);
            }
            else{
                botaoExcluir.setEnabled(false);
                botaoAlterar.setEnabled(false);
                botaoAdicionar.setEnabled(true);
            }
        }
    };
    
    private void limparCampos(){
        campoNome.setText("");
        campoID.setText("");
        campoPreco.setText("");
        campoDescricao.setText("");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        separadorCabecalho = new javax.swing.JSeparator();
        separadorRodape = new javax.swing.JSeparator();
        botaoAdicionar = new javax.swing.JButton();
        Pesquisar = new javax.swing.JButton();
        botaoExcluir = new javax.swing.JButton();
        campoDeBusca = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabela = new javax.swing.JTable();
        labelNome = new javax.swing.JLabel();
        campoNome = new javax.swing.JTextField();
        labelPreco = new javax.swing.JLabel();
        campoPreco = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        campoDescricao = new javax.swing.JTextArea();
        botaoAlterar = new javax.swing.JButton();
        labelDescricao = new javax.swing.JLabel();
        labelID = new javax.swing.JLabel();
        campoID = new javax.swing.JTextField();
        botaoLimpar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Loja BD");
        setAlwaysOnTop(true);

        botaoAdicionar.setText("Adicionar");
        botaoAdicionar.setMaximumSize(new java.awt.Dimension(75, 30));
        botaoAdicionar.setMinimumSize(new java.awt.Dimension(75, 30));
        botaoAdicionar.setPreferredSize(new java.awt.Dimension(80, 30));
        botaoAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAdicionarActionPerformed(evt);
            }
        });

        Pesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/magnifier.png"))); // NOI18N
        Pesquisar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PesquisarMouseClicked(evt);
            }
        });
        Pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PesquisarActionPerformed(evt);
            }
        });

        botaoExcluir.setText("Excluir");
        botaoExcluir.setEnabled(false);
        botaoExcluir.setPreferredSize(new java.awt.Dimension(80, 30));
        botaoExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoExcluirActionPerformed(evt);
            }
        });

        campoDeBusca.setText("Pesquise o produto");
        campoDeBusca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campoDeBuscaMouseClicked(evt);
            }
        });
        campoDeBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoDeBuscaActionPerformed(evt);
            }
        });

        Tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        Tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelaMouseClicked(evt);
            }
        });
        Tabela.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TabelaKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(Tabela);

        labelNome.setText("Nome:");

        labelPreco.setText("Preço:");

        campoDescricao.setColumns(20);
        campoDescricao.setRows(5);
        jScrollPane2.setViewportView(campoDescricao);

        botaoAlterar.setText("Alterar");
        botaoAlterar.setEnabled(false);
        botaoAlterar.setPreferredSize(new java.awt.Dimension(80, 30));
        botaoAlterar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoAlterarMouseClicked(evt);
            }
        });

        labelDescricao.setText("Descrição:");

        labelID.setText("ID:");

        campoID.setEditable(false);
        campoID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoIDActionPerformed(evt);
            }
        });
        campoID.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                campoIDPropertyChange(evt);
            }
        });

        botaoLimpar.setText("Limpar");
        botaoLimpar.setPreferredSize(new java.awt.Dimension(80, 30));
        botaoLimpar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoLimparMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(separadorCabecalho, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(separadorRodape, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(campoDeBusca, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelDescricao)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(labelPreco)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(campoPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(90, 90, 90)
                            .addComponent(labelID, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(campoID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(botaoLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                            .addComponent(botaoExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(15, 15, 15)
                            .addComponent(botaoAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(15, 15, 15)
                            .addComponent(botaoAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(labelNome)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(campoNome))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)))
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(separadorCabecalho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(campoDeBusca, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                            .addComponent(Pesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(15, 15, 15)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelNome, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addComponent(labelDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botaoAlterar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(botaoExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(botaoAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(botaoLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(15, 15, 15)
                .addComponent(separadorRodape, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAdicionarActionPerformed
        try {
            PreparedStatement pst = ConectaBanco.conn.prepareStatement("insert into Produto (nomeProduto, precoProduto, descricaoProduto) values(?, ?, ?);");
            pst.setString(1, campoNome.getText());
            pst.setString(2, campoPreco.getText());
            pst.setString(3, campoDescricao.getText());
            pst.executeUpdate();
            
            JOptionPane.showMessageDialog(rootPane, "Adicionado com Sucesso!");
            preencherTabela("select * from Produto order by idProduto;");
            limparCampos();            
        }
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane,"Erro ao Adicionar!\n ERRO: " + ex);
        }
    }//GEN-LAST:event_botaoAdicionarActionPerformed

    private void botaoExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoExcluirActionPerformed
        if(campoID.getText().length() > 0){
            try {
                PreparedStatement pst = ConectaBanco.conn.prepareStatement("delete from  Produto where idProduto = ?;");
                pst.setString(1, campoID.getText());
                pst.execute();

                JOptionPane.showMessageDialog(rootPane, "Excluído com Sucesso!");
                preencherTabela("select * from Produto order by idProduto;");
                limparCampos();
            }
            catch (SQLException ex) {
                JOptionPane.showMessageDialog(rootPane,"Erro ao Excluir!\n ERRO: " + ex);
            }
        }
    }//GEN-LAST:event_botaoExcluirActionPerformed

    private void campoIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoIDActionPerformed
        campoID.setText("");
    }//GEN-LAST:event_campoIDActionPerformed

    private void campoDeBuscaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoDeBuscaMouseClicked
        campoDeBusca.setText("");
    }//GEN-LAST:event_campoDeBuscaMouseClicked

    private void PesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PesquisarActionPerformed

    private void PesquisarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PesquisarMouseClicked
        if(campoDeBusca.getText().length()> 0){
            for(int i = 0; i < Tabela.getRowCount();i++){
                if(campoDeBusca.getText().equals(Tabela.getValueAt(i, 1))){
                    campoNome.setText(Tabela.getValueAt(i, 1).toString());
                    campoPreco.setText(Tabela.getValueAt(i, 2).toString());
                    campoID.setText(Tabela.getValueAt(i, 0).toString());                    
                    campoDescricao.setText(Tabela.getValueAt(i, 3).toString());
                }
            }
        }
    }//GEN-LAST:event_PesquisarMouseClicked

    private void botaoLimparMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoLimparMouseClicked
        limparCampos();
    }//GEN-LAST:event_botaoLimparMouseClicked

    private void TabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaMouseClicked
        int linha = Tabela.getSelectedRow();
        campoID.setText(Tabela.getValueAt(linha, 0).toString());
        campoNome.setText(Tabela.getValueAt(linha, 1).toString());
        campoPreco.setText(Tabela.getValueAt(linha, 2).toString());
        campoDescricao.setText(Tabela.getValueAt(linha, 3).toString());
    }//GEN-LAST:event_TabelaMouseClicked

    private void botaoAlterarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoAlterarMouseClicked
        if(campoID.getText().length() > 0){
            try {
                PreparedStatement pst = ConectaBanco.conn.prepareStatement("update Produto set nomeProduto = ?, precoProduto = ?, descricaoProduto = ? where idProduto = ?;");
                pst.setString(1, campoNome.getText());
                pst.setString(2, campoPreco.getText());
                pst.setString(3, campoDescricao.getText());
                pst.setString(4, campoID.getText());
                pst.execute();

                JOptionPane.showMessageDialog(rootPane, "Alterado com Sucesso!");
                preencherTabela("select * from Produto order by idProduto;");
                limparCampos();
            }
            catch (SQLException ex) {
                JOptionPane.showMessageDialog(rootPane,"Erro ao Alterar!\n ERRO: " + ex);
            }
        }
    }//GEN-LAST:event_botaoAlterarMouseClicked

    private void TabelaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TabelaKeyReleased
        int linha = Tabela.getSelectedRow();
        campoID.setText(Tabela.getValueAt(linha, 0).toString());
        campoNome.setText(Tabela.getValueAt(linha, 1).toString());
        campoPreco.setText(Tabela.getValueAt(linha, 2).toString());
        campoDescricao.setText(Tabela.getValueAt(linha, 3).toString());
    }//GEN-LAST:event_TabelaKeyReleased

    private void campoIDPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_campoIDPropertyChange

    }//GEN-LAST:event_campoIDPropertyChange

    private void campoDeBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoDeBuscaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoDeBuscaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Pesquisar;
    private javax.swing.JTable Tabela;
    private javax.swing.JButton botaoAdicionar;
    private javax.swing.JButton botaoAlterar;
    private javax.swing.JButton botaoExcluir;
    private javax.swing.JButton botaoLimpar;
    private javax.swing.JTextField campoDeBusca;
    private javax.swing.JTextArea campoDescricao;
    private javax.swing.JTextField campoID;
    private javax.swing.JTextField campoNome;
    private javax.swing.JTextField campoPreco;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelDescricao;
    private javax.swing.JLabel labelID;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelPreco;
    private javax.swing.JSeparator separadorCabecalho;
    private javax.swing.JSeparator separadorRodape;
    // End of variables declaration//GEN-END:variables
}
